version: '3'
services:
  static:
    build: .
    image: local/static.sngsk.info:latest
    restart: always
    ports:
      - "127.0.0.1:8081:8081"
  top:
    build: ./top
    image: local/sngsk.info:latest
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - static
